language: bash
env:
  global:
    - TRAVIS_USER_ID=$(id -u)
    - TRAVIS_GROUP_ID=$(id -g)

before_install:
  - "sed -i \"s#www_data_uid: 1000#www_data_uid: $TRAVIS_USER_ID#\" ./docker-compose.yml"
  - "sed -i \"s#www_data_gid: 1000#www_data_gid: $TRAVIS_GROUP_ID#\" ./docker-compose.yml"

install:

  - docker-compose pull --parallel webserver php-fpm
  - docker-compose build --parallel webserver php-fpm
  - docker-compose up -d webserver php-fpm
  - docker-compose exec php-fpm composer install --no-interaction
  - docker-compose exec php-fpm Tests/app/bin/console assets:install -v Tests/app
  - docker-compose exec -w /application/Tests/app php-fpm npm ci
  - docker-compose exec -w /application/Tests/app php-fpm npm run build
  - docker-compose exec php-fpm npm ci

script:
  - docker-compose exec php-fpm npm run test
